### PR TITLE
Support multiple tickers

### PR DESCRIPTION
**Pull request by stantoncbradley**
Support multiple tickers by dynamically creating ws events based on ticket instead of 'quote'
add package.json & remove node_modules
add CORS
set server to listen on process.env.PORT || 4000

### CODE REVIEW

**Comment by nodesocket** [comment]
@stantoncbradley I merged in your changes as well as refactor the entire project. Can you pull latest.

I'm not seeing how you can provide multiple tickers with your PR though. Also, updating the ticker in the url does not take effect unless you refresh the page.

**Comment by stantoncbradley** [comment]
thanks, will do!  The backend supports multiple tickers, whenever you send a new ticket it will start long polling and emitting for that ticker in addition to the existing tickers.  I don't use this app's index page but connect to my react client (https://github.com/stantoncbradley/ticker-tracker), so I didn't add ui support.  I can check why the url doesn't work anymore tho

**Comment by nodesocket** [comment]
@stantoncbradley just checked out your React app. Very nice job! Did you just build this for fun?

screen shot 2016-10-24 at 1 11 33 pm

**Comment by stantoncbradley** [comment]
@nodesocket thanks! A little bit of both--put it together to demo react/ws for my company. It was fun too tho 😆

Thanks for putting together this node app, exactly what I needed!

**Pull request merged**
